export const socialLinks = [
    { id: '1', name: 'Instagram', icon: 'logo-instagram', color: '#E4405F' },
    { id: '2', name: 'Whatsapp', icon: 'logo-whatsapp', color: '#25D366' },
    { id: '3', name: 'Facebook', icon: 'logo-facebook', color: '#1877F2' },
    { id: '4', name: 'Twitter', icon: 'logo-twitter', color: '#1DA1F2' },
    { id: '5', name: 'Website', icon: 'globe-outline' },
    { id: '7', name: 'Tiktok', icon: 'logo-tiktok', color: '#EE1D51' },
    { id: '8', name: 'Threads', icon: 'logo-instagram', color: '#1DA1F2' },
    { id: '9', name: 'Telegram', icon: 'paper-plane-outline', color: '#1AB7EA' },
    { id: '10', name: 'Snapchat', icon: 'logo-snapchat', color: '#FFFC00' },
    { id: '11', name: 'Twitch', icon: 'logo-twitch', color: '#9146ff' },
    { id: '12', name: 'SoundCloud', icon: 'musical-notes-outline', color: '1DA1F2' },
    { id: '13', name: 'Skype', icon: 'logo-skype', color: '#00aff0' },
    { id: '14', name: 'Reddit', icon: 'logo-reddit', color: '#ff4500' },
    { id: '15', name: 'Phone', icon: 'call-outline', color: '#000' },
    { id: '16', name: 'Email', icon: 'mail-outline', color: '#000' },
  ];